'use client'

import Link from 'next/link'
import { KeyRound, Laptop, LockKeyhole, MapPin, ShieldAlert, ShieldCheck, UserRoundCog } from 'lucide-react'
import { useState } from 'react'
import { usePortal } from '@/components/portal/PortalProvider'
import { EmptyState, PageHeader, Panel, StatusPill, formatDateTime } from '@/components/portal/PortalUi'

export default function SecurityPage() {
  const { users, organizations, sessions } = usePortal()
  const [now] = useState(() => Date.now())
  const activeUsers = users.filter((user) => user.is_active)
  const admins = activeUsers.filter((user) => ['owner', 'administrator'].includes(user.platform_role || 'administrator'))
  const dormant = activeUsers.filter((user) => user.portal_last_active_at && now - new Date(user.portal_last_active_at).getTime() > 30 * 86400000)
  const suspended = organizations.filter((organization) => organization.status === 'suspended')
  const activeSessions = sessions.filter((session) => now - new Date(session.last_seen_at).getTime() < 24 * 3600000)
  return <div className="space-y-6"><PageHeader eyebrow="Trust and control" title="Security centre" description="Privileged access, recent devices, operator activity, and tenant-level security intervention." />
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><SecurityStat icon={<UserRoundCog />} label="Active operators" value={activeUsers.length} /><SecurityStat icon={<KeyRound />} label="Administrators" value={admins.length} /><SecurityStat icon={<Laptop />} label="24-hour sessions" value={activeSessions.length} /><SecurityStat icon={<LockKeyhole />} label="Dormant access" value={dormant.length} warning={dormant.length > 0} /><SecurityStat icon={<ShieldAlert />} label="Suspended tenants" value={suspended.length} warning={suspended.length > 0} /></section>
    <section className="grid gap-5 xl:grid-cols-2"><Panel title="Privileged access review" description="Administrators with broad platform authority.">{admins.length ? <div className="divide-y divide-black/5">{admins.map((user) => <Link key={user.id} href="/portal/users" className="flex items-center gap-3 py-3 first:pt-0 last:pb-0"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#152019] font-black text-[#b8f43d]">{user.full_name[0]}</span><div className="min-w-0 flex-1"><p className="truncate text-sm font-black">{user.full_name}</p><p className="truncate text-xs text-[#718078]">{user.email} · last active {formatDateTime(user.portal_last_active_at)}</p></div><StatusPill value={user.platform_role || 'administrator'} /></Link>)}</div> : <EmptyState title="No privileged operators" description="Administrator accounts will appear here." />}</Panel><Panel title="Tenant intervention" description="Organizations currently blocked from normal access.">{suspended.length ? <div className="space-y-3">{suspended.map((organization) => <Link key={organization.id} href={`/portal/organizations/${organization.id}`} className="flex items-center gap-3 rounded-xl border border-red-100 bg-red-50 p-3"><ShieldCheck className="h-4 w-4 text-red-700" /><div className="min-w-0 flex-1"><p className="truncate text-sm font-black">{organization.name}</p><p className="text-xs text-red-700/70">{organization.plan_name} · {organization.staff_count} staff records</p></div><StatusPill value="suspended" /></Link>)}</div> : <EmptyState title="No suspended tenants" description="All organizations currently have normal access." />}</Panel></section>
    <Panel title="Recent session and device history" description="Latest observed platform and tenant sessions. IP and device data are security-sensitive and audit-visible.">{sessions.length ? <div className="overflow-x-auto"><table className="w-full min-w-[850px] text-left"><thead><tr className="border-b border-black/8 text-[10px] font-black uppercase tracking-[.12em] text-[#718078]"><th className="py-3 pr-4">Person</th><th className="px-4 py-3">Organization</th><th className="px-4 py-3">Device</th><th className="px-4 py-3">Location / IP</th><th className="py-3 pl-4 text-right">Last seen</th></tr></thead><tbody>{sessions.slice(0, 40).map((session) => <tr key={session.id} className="border-b border-black/5 last:border-0"><td className="py-3 pr-4"><p className="text-sm font-black">{session.profile?.full_name || 'Unknown profile'}</p><p className="text-xs text-[#718078]">{session.profile?.email || 'No email recorded'}</p></td><td className="px-4 py-3 text-xs font-bold">{session.organization?.name || 'Platform'}</td><td className="px-4 py-3 text-xs font-bold">{session.device_name || 'Unknown device'}</td><td className="px-4 py-3"><p className="flex items-center gap-1 text-xs font-bold"><MapPin className="h-3 w-3" />{session.location_label || 'Unknown location'}</p><p className="mt-1 font-mono text-[10px] text-[#718078]">{session.ip_address || 'IP unavailable'}</p></td><td className="py-3 pl-4 text-right text-xs font-bold text-[#718078]">{formatDateTime(session.last_seen_at)}</td></tr>)}</tbody></table></div> : <EmptyState title="No session history" description="Device activity will appear after authenticated sessions are recorded." />}</Panel>
  </div>
}

function SecurityStat({ icon, label, value, warning = false }: { icon: React.ReactNode; label: string; value: number; warning?: boolean }) { return <article className={`rounded-[22px] border p-5 ${warning ? 'border-amber-200 bg-amber-50' : 'border-black/10 bg-white'}`}><div className="flex justify-between"><p className="text-[10px] font-black uppercase tracking-[.14em] opacity-55">{label}</p><span className="[&>svg]:h-4 [&>svg]:w-4 opacity-55">{icon}</span></div><p className="mt-4 text-3xl font-black">{value}</p></article> }
