'use client'

import { Bell, Check, KeyRound, LockKeyhole, Save, ShieldCheck } from 'lucide-react'
import { useEffect, useState } from 'react'
import { usePortal } from '@/components/portal/PortalProvider'
import { PageHeader, Panel, StatusPill } from '@/components/portal/PortalUi'

const approvalOptions = ['owner_change', 'admin_role_change', 'bulk_disable', 'mfa_reset', 'billing_refund', 'tenant_suspension']

export default function SettingsPage() {
  const { access, governanceSettings, refresh } = usePortal()
  const [form, setForm] = useState({ approval_required_for: [] as string[], audit_retention_days: 2555, support_first_response_minutes: 240, support_resolution_minutes: 1440, notification_policy: { sla_breach: true, billing_risk: true, security_event: true, daily_digest: false } as Record<string, boolean> })
  const [saving, setSaving] = useState(false)
  const [feedback, setFeedback] = useState('')
  useEffect(() => { if (governanceSettings) setForm({ approval_required_for: governanceSettings.approval_required_for || [], audit_retention_days: governanceSettings.audit_retention_days, support_first_response_minutes: governanceSettings.support_first_response_minutes, support_resolution_minutes: governanceSettings.support_resolution_minutes, notification_policy: governanceSettings.notification_policy || {} }) }, [governanceSettings])
  const save = async (event: React.FormEvent) => { event.preventDefault(); setSaving(true); setFeedback(''); try { const response = await fetch('/api/portal/maturity', { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ ...form, confirmation: 'CONFIRM' }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error || 'Unable to save governance settings.'); setFeedback('Governance policy saved and audited.'); await refresh() } catch (caught) { setFeedback(caught instanceof Error ? caught.message : 'Unable to save governance settings.') } finally { setSaving(false) } }
  const toggleApproval = (value: string) => setForm((current) => ({ ...current, approval_required_for: current.approval_required_for.includes(value) ? current.approval_required_for.filter((item) => item !== value) : [...current.approval_required_for, value] }))

  return <div className="space-y-6"><PageHeader eyebrow="Platform governance" title="Portal settings" description="Configure approval thresholds, retention, service targets, and the notification policy enforced across platform operations." />
    {feedback ? <p role="status" className="rounded-xl border border-[#a9cf5b] bg-[#e9f6cc] px-4 py-3 text-sm font-bold text-[#496126]">{feedback}</p> : null}
    <section className="grid gap-5 xl:grid-cols-[.8fr_1.2fr]"><div className="space-y-5"><Panel title="Your access" description="Effective role and permissions for this portal session."><div className="flex items-center gap-3 rounded-xl bg-[#152019] p-4 text-white"><span className="flex h-11 w-11 items-center justify-center rounded-xl bg-[#b8f43d] font-black text-[#152019]">{access?.full_name?.[0] || 'P'}</span><div className="min-w-0 flex-1"><p className="truncate font-black">{access?.full_name || 'Portal operator'}</p><p className="truncate text-xs text-white/45">{access?.email}</p></div><StatusPill value={access?.platform_role || 'administrator'} /></div><div className="mt-4 space-y-2">{access?.platform_permissions.map((permission) => <div key={permission} className="flex items-center gap-2 rounded-lg bg-[#f7f8f5] px-3 py-2 text-xs font-bold"><Check className="h-3.5 w-3.5 text-[#66814a]" />{permission}</div>)}</div></Panel><Panel title="Security baseline"><Control icon={<LockKeyhole />} title="Audited mutations" detail="Every privileged change is written to the audit trail." /><Control icon={<KeyRound />} title="Explicit confirmation" detail="High-risk actions require deliberate confirmation." /><Control icon={<ShieldCheck />} title="Service-role isolation" detail="Platform operations remain isolated from tenant sessions." /><Control icon={<Bell />} title="Risk notifications" detail="Operational alerts derive from live platform state." /></Panel></div>
      <Panel title="Governance policy" description="Changes take effect across platform operations and are recorded in the audit trail."><form onSubmit={save} className="space-y-6"><div><h3 className="text-sm font-black">Actions requiring approval</h3><div className="mt-3 grid gap-2 sm:grid-cols-2">{approvalOptions.map((option) => <label key={option} className="flex items-center gap-3 rounded-xl border border-black/8 p-3 text-xs font-bold capitalize"><input type="checkbox" checked={form.approval_required_for.includes(option)} onChange={() => toggleApproval(option)} className="h-4 w-4 accent-[#78924e]" />{option.replaceAll('_', ' ')}</label>)}</div></div><div className="grid gap-3 sm:grid-cols-3"><NumberField label="Audit retention (days)" value={form.audit_retention_days} min={90} max={3650} onChange={(value) => setForm((current) => ({ ...current, audit_retention_days: value }))} /><NumberField label="First response (minutes)" value={form.support_first_response_minutes} min={15} max={10080} onChange={(value) => setForm((current) => ({ ...current, support_first_response_minutes: value }))} /><NumberField label="Resolution target (minutes)" value={form.support_resolution_minutes} min={60} max={43200} onChange={(value) => setForm((current) => ({ ...current, support_resolution_minutes: value }))} /></div><div><h3 className="text-sm font-black">Notification policy</h3><div className="mt-3 grid gap-2 sm:grid-cols-2">{Object.entries(form.notification_policy).map(([key, enabled]) => <label key={key} className="flex items-center justify-between rounded-xl bg-[#f7f8f5] p-3 text-xs font-bold capitalize"><span>{key.replaceAll('_', ' ')}</span><input type="checkbox" checked={enabled} onChange={(event) => setForm((current) => ({ ...current, notification_policy: { ...current.notification_policy, [key]: event.target.checked } }))} className="h-4 w-4 accent-[#78924e]" /></label>)}</div></div><button disabled={saving || !access?.canManageOperations} className="inline-flex items-center gap-2 rounded-xl bg-[#152019] px-4 py-3 text-sm font-black text-white disabled:opacity-40"><Save className="h-4 w-4" />{saving ? 'Saving…' : 'Save governance policy'}</button></form></Panel></section>
  </div>
}

function NumberField({ label, value, min, max, onChange }: { label: string; value: number; min: number; max: number; onChange: (value: number) => void }) { return <label className="text-[10px] font-black uppercase tracking-wide text-[#718078]">{label}<input type="number" value={value} min={min} max={max} onChange={(event) => onChange(Number(event.target.value))} className="mt-1 h-11 w-full rounded-xl border border-black/10 bg-white px-3 text-sm font-bold text-[#152019]" /></label> }
function Control({ icon, title, detail }: { icon: React.ReactNode; title: string; detail: string }) { return <div className="flex gap-3 border-b border-black/5 py-3 last:border-0 last:pb-0"><span className="mt-0.5 [&>svg]:h-4 [&>svg]:w-4 text-[#78924e]">{icon}</span><div><p className="text-sm font-black">{title}</p><p className="mt-1 text-xs leading-5 text-[#718078]">{detail}</p></div></div> }
