'use client'

import { useState } from 'react'
import { CheckCircle2, Clock3, Plus, ShieldQuestion } from 'lucide-react'
import { usePortal } from '@/components/portal/PortalProvider'
import { EmptyState, PageHeader, Panel, StatusPill, formatDateTime } from '@/components/portal/PortalUi'

export default function TasksPage() {
  const { tasks, approvals, organizations, agents, access, taskComments, refresh } = usePortal()
  const [showCreate, setShowCreate] = useState(false)
  const [saving, setSaving] = useState(false)
  const [note, setNote] = useState('')
  const [commentTaskId, setCommentTaskId] = useState('')
  const [comment, setComment] = useState('')
  const [form, setForm] = useState({ organization_id: '', title: '', description: '', priority: 'normal', due_at: '', assigned_to_profile_id: '' })
  const activeTasks = tasks.filter((task) => !['completed', 'cancelled'].includes(task.status))
  const pending = approvals.filter((approval) => approval.status === 'pending')
  const mutate = async (payload: Record<string, unknown>) => { setSaving(true); const response = await fetch('/api/portal/operations', { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ ...payload, confirmation: 'CONFIRM' }) }); if (response.ok) { setNote(''); await refresh() }; setSaving(false) }
  const create = async (event: React.FormEvent) => { event.preventDefault(); setSaving(true); const response = await fetch('/api/portal/operations', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(form) }); if (response.ok) { setShowCreate(false); setForm({ organization_id: '', title: '', description: '', priority: 'normal', due_at: '', assigned_to_profile_id: '' }); await refresh() }; setSaving(false) }
  const addComment = async (event: React.FormEvent) => { event.preventDefault(); if (!commentTaskId || !comment.trim()) return; setSaving(true); const response = await fetch('/api/portal/maturity', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ kind: 'task_comment', task_id: commentTaskId, message: comment }) }); if (response.ok) { setComment(''); await refresh() }; setSaving(false) }
  return <div className="space-y-6"><PageHeader eyebrow="Operational accountability" title="Tasks and approvals" description="Assign customer follow-ups, track deadlines, and review high-risk platform actions." action={access?.canManageOperations ? <button onClick={() => setShowCreate((value) => !value)} className="inline-flex items-center gap-2 rounded-xl bg-[#152019] px-4 py-3 text-sm font-black text-white"><Plus className="h-4 w-4" />New task</button> : undefined} />
    {showCreate ? <form onSubmit={create} className="grid gap-3 rounded-[24px] border border-[#8caf42] bg-[#dff7a8] p-5 lg:grid-cols-6"><select required value={form.organization_id} onChange={(event) => setForm({ ...form, organization_id: event.target.value })} className="h-11 rounded-xl border border-black/10 bg-white px-3 text-sm font-bold"><option value="">Organization</option>{organizations.map((organization) => <option key={organization.id} value={organization.id}>{organization.name}</option>)}</select><input required minLength={3} value={form.title} onChange={(event) => setForm({ ...form, title: event.target.value })} placeholder="Follow-up task" className="h-11 rounded-xl border border-black/10 bg-white px-3 text-sm lg:col-span-2" /><select value={form.priority} onChange={(event) => setForm({ ...form, priority: event.target.value })} className="h-11 rounded-xl border border-black/10 bg-white px-3 text-sm font-bold"><option value="normal">Normal</option><option value="high">High</option><option value="urgent">Urgent</option><option value="low">Low</option></select><input type="datetime-local" value={form.due_at} onChange={(event) => setForm({ ...form, due_at: event.target.value })} className="h-11 rounded-xl border border-black/10 bg-white px-3 text-sm" /><button disabled={saving} className="h-11 rounded-xl bg-[#152019] text-sm font-black text-white disabled:opacity-50">Create task</button><textarea value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} placeholder="Context and expected outcome" rows={3} className="rounded-xl border border-black/10 bg-white p-3 text-sm lg:col-span-4" /><select value={form.assigned_to_profile_id} onChange={(event) => setForm({ ...form, assigned_to_profile_id: event.target.value })} className="rounded-xl border border-black/10 bg-white px-3 text-sm font-bold lg:col-span-2"><option value="">Unassigned</option>{agents.map((agent) => <option key={agent.id} value={agent.id}>{agent.full_name}</option>)}</select></form> : null}
    <section className="grid gap-5 xl:grid-cols-[1.15fr_.85fr]"><Panel title="Active work queue" description={`${activeTasks.length} tasks require ownership or completion.`}>{activeTasks.length ? <div className="space-y-3">{activeTasks.map((task) => <article key={task.id} className="rounded-xl border border-black/8 bg-[#f8faf6] p-4"><div className="flex flex-wrap items-start gap-3"><Clock3 className="mt-0.5 h-4 w-4 text-[#78924e]" /><div className="min-w-0 flex-1"><p className="text-sm font-black">{task.title}</p><p className="mt-1 text-xs text-[#718078]">{task.organization?.name} · {task.assignee?.full_name || 'Unassigned'}{task.due_at ? ` · due ${formatDateTime(task.due_at)}` : ''}</p></div><StatusPill value={task.priority} /><StatusPill value={task.status} /></div>{access?.canManageOperations ? <div className="mt-3 flex justify-end gap-2"><button disabled={saving} onClick={() => void mutate({ kind: 'task', id: task.id, status: 'in_progress' })} className="rounded-lg bg-white px-3 py-2 text-xs font-black ring-1 ring-black/10">Start</button><button disabled={saving} onClick={() => void mutate({ kind: 'task', id: task.id, status: 'completed' })} className="rounded-lg bg-[#152019] px-3 py-2 text-xs font-black text-white">Complete</button></div> : null}</article>)}</div> : <EmptyState title="Work queue is clear" description="New operational tasks will appear here." />}</Panel>
      <Panel title="Approval queue" description={`${pending.length} high-risk actions await a decision.`}>{pending.length ? <div className="space-y-4">{pending.map((approval) => <article key={approval.id} className="rounded-xl border border-amber-200 bg-amber-50 p-4"><div className="flex items-start gap-3"><ShieldQuestion className="mt-0.5 h-5 w-5 text-amber-700" /><div className="min-w-0 flex-1"><p className="text-sm font-black capitalize">{approval.action_type.replaceAll('_', ' ')}</p><p className="mt-1 text-xs text-amber-800/70">{approval.organization?.name || 'Platform-wide'} · requested {formatDateTime(approval.created_at)}</p></div></div>{access?.canManageOperations ? <div className="mt-3"><input value={note} onChange={(event) => setNote(event.target.value)} placeholder="Required review note" className="h-10 w-full rounded-lg border border-amber-200 bg-white px-3 text-xs" /><div className="mt-2 flex justify-end gap-2"><button disabled={saving || note.trim().length < 3} onClick={() => void mutate({ kind: 'approval', id: approval.id, status: 'rejected', review_note: note })} className="rounded-lg bg-white px-3 py-2 text-xs font-black text-red-700 ring-1 ring-red-200">Reject</button><button disabled={saving || note.trim().length < 3} onClick={() => void mutate({ kind: 'approval', id: approval.id, status: 'approved', review_note: note })} className="inline-flex items-center gap-1 rounded-lg bg-[#152019] px-3 py-2 text-xs font-black text-white"><CheckCircle2 className="h-3.5 w-3.5" />Approve</button></div></div> : null}</article>)}</div> : <EmptyState title="No pending approvals" description="High-risk requests will appear here for review." />}</Panel></section>
    <Panel title="Task collaboration" description="Add durable context and hand-off notes to active operational work."><form onSubmit={addComment} className="grid gap-3 sm:grid-cols-[260px_1fr_auto]"><select required value={commentTaskId} onChange={(event) => setCommentTaskId(event.target.value)} className="h-11 rounded-xl border border-black/10 bg-white px-3 text-sm font-bold"><option value="">Select active task</option>{activeTasks.map((task) => <option key={task.id} value={task.id}>{task.title}</option>)}</select><input required value={comment} onChange={(event) => setComment(event.target.value)} placeholder="Add hand-off context or an update" className="h-11 rounded-xl border border-black/10 bg-[#f7f8f5] px-3 text-sm" /><button disabled={saving} className="rounded-xl bg-[#152019] px-4 text-xs font-black text-white">Add comment</button></form>{commentTaskId ? <div className="mt-4 space-y-2">{taskComments.filter((item) => item.task_id === commentTaskId).map((item) => <div key={item.id} className="rounded-xl bg-[#f7f8f5] p-3"><div className="flex justify-between gap-3"><p className="text-xs font-black">{item.author?.full_name || 'Former operator'}</p><span className="text-[10px] font-bold text-[#718078]">{formatDateTime(item.created_at)}</span></div><p className="mt-2 text-sm text-[#4f5c54]">{item.message}</p></div>)}</div> : null}</Panel>
  </div>
}
