import type { ReactNode } from 'react'

export function PageHeader({ eyebrow, title, description, action }: { eyebrow: string; title: string; description: string; action?: ReactNode }) { return <header className="flex flex-col gap-4 border-b border-black/10 pb-6 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-[10px] font-black uppercase tracking-[0.2em] text-[#66814a]">{eyebrow}</p><h1 className="mt-2 text-3xl font-black tracking-[-0.045em] text-[#152019] sm:text-4xl">{title}</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-[#68746c]">{description}</p></div>{action}</header> }
export function Panel({ title, description, children, className = '' }: { title: string; description?: string; children: ReactNode; className?: string }) { return <section className={`rounded-[24px] border border-black/10 bg-white p-5 shadow-[0_18px_55px_rgba(20,31,24,0.06)] sm:p-6 ${className}`}><div className="mb-5"><h2 className="text-lg font-black tracking-[-0.025em] text-[#152019]">{title}</h2>{description ? <p className="mt-1 text-sm text-[#718078]">{description}</p> : null}</div>{children}</section> }
export function StatusPill({ value }: { value: string }) { const risk = ['suspended', 'cancelled', 'urgent', 'overdue', 'inactive'].includes(value); const good = ['active', 'resolved', 'completed', 'trialing'].includes(value); return <span className={`inline-flex rounded-full px-2.5 py-1 text-[10px] font-black uppercase tracking-[0.08em] ${risk ? 'bg-red-50 text-red-700' : good ? 'bg-[#e9f6cc] text-[#496126]' : 'bg-slate-100 text-slate-600'}`}>{value.replaceAll('_', ' ')}</span> }
export function LoadingState() { return <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[0, 1, 2, 3].map((item) => <div key={item} className="h-36 animate-pulse rounded-[24px] border border-black/5 bg-white" />)}</div> }
export function EmptyState({ title, description }: { title: string; description: string }) { return <div className="rounded-2xl border border-dashed border-black/15 bg-[#f7f8f5] px-5 py-12 text-center"><p className="font-black text-[#263229]">{title}</p><p className="mt-1 text-sm text-[#718078]">{description}</p></div> }
export function formatDate(value: string | null) { if (!value) return 'Not recorded'; return new Intl.DateTimeFormat('en-GB', { day: '2-digit', month: 'short', year: 'numeric' }).format(new Date(value)) }
export function formatDateTime(value: string | null) { if (!value) return 'Not recorded'; return new Intl.DateTimeFormat('en-GB', { day: '2-digit', month: 'short', hour: '2-digit', minute: '2-digit' }).format(new Date(value)) }
