'use client'

import Link from 'next/link'
import { ChevronRight, Search } from 'lucide-react'
import { useMemo, useState } from 'react'
import { usePortal } from '@/components/portal/PortalProvider'
import { EmptyState, LoadingState, PageHeader, StatusPill } from '@/components/portal/PortalUi'

export default function OrganizationsPage() {
  const { organizations, loading } = usePortal()
  const [search, setSearch] = useState('')
  const [status, setStatus] = useState('all')
  const filtered = useMemo(() => organizations.filter((organization) => { const query = search.toLowerCase().trim(); return (status === 'all' || organization.status === status) && (!query || [organization.name, organization.slug, organization.plan].some((value) => value.toLowerCase().includes(query))) }), [organizations, search, status])
  return <div className="space-y-6"><PageHeader eyebrow="Tenant operations" title="Organizations" description="Search every customer account, assess utilization, and open a complete operational record." />
    <section className="rounded-[24px] border border-black/10 bg-white shadow-[0_18px_55px_rgba(20,31,24,0.06)]"><div className="flex flex-col gap-3 border-b border-black/10 p-4 sm:flex-row sm:items-center"><label className="flex min-w-0 flex-1 items-center gap-2 rounded-xl border border-black/10 bg-[#f7f8f5] px-3"><Search className="h-4 w-4 text-[#718078]" /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search by name, slug, or plan" className="h-11 min-w-0 flex-1 bg-transparent text-sm outline-none" /></label><select value={status} onChange={(event) => setStatus(event.target.value)} className="h-11 rounded-xl border border-black/10 bg-white px-3 text-sm font-bold"><option value="all">All statuses</option><option value="active">Active</option><option value="trialing">Trialing</option><option value="paused">Paused</option><option value="suspended">Suspended</option></select></div>
      {loading && !organizations.length ? <div className="p-5"><LoadingState /></div> : filtered.length ? <div className="overflow-x-auto"><table className="w-full min-w-[820px] text-left"><thead><tr className="border-b border-black/8 text-[10px] font-black uppercase tracking-[0.12em] text-[#718078]"><th className="px-5 py-3">Organization</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Plan</th><th className="px-4 py-3">Users</th><th className="px-4 py-3">Staff capacity</th><th className="px-5 py-3 text-right">Open</th></tr></thead><tbody>{filtered.map((organization) => <tr key={organization.id} className="border-b border-black/5 last:border-0 hover:bg-[#f8faf6]"><td className="px-5 py-4"><div className="flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#152019] font-black text-[#b8f43d]">{organization.name[0]}</span><div><p className="text-sm font-black">{organization.name}</p><p className="mt-0.5 font-mono text-[11px] text-[#718078]">/{organization.slug}</p></div></div></td><td className="px-4 py-4"><StatusPill value={organization.status} /></td><td className="px-4 py-4 text-sm font-bold">{organization.plan_name}</td><td className="px-4 py-4 text-sm font-bold">{organization.user_count}{organization.user_limit ? ` / ${organization.user_limit}` : ''}</td><td className="px-4 py-4"><p className="text-sm font-bold">{organization.staff_count}{organization.staff_limit ? ` / ${organization.staff_limit}` : ''}</p>{organization.staff_limit ? <div className="mt-2 h-1.5 w-28 overflow-hidden rounded-full bg-black/8"><span className="block h-full rounded-full bg-[#8aae3d]" style={{ width: `${Math.min(100, organization.staff_count / organization.staff_limit * 100)}%` }} /></div> : null}</td><td className="px-5 py-4 text-right"><Link href={`/portal/organizations/${organization.id}`} aria-label={`Open ${organization.name}`} className="inline-flex rounded-lg border border-black/10 p-2 hover:bg-[#eef1eb]"><ChevronRight className="h-4 w-4" /></Link></td></tr>)}</tbody></table></div> : <div className="p-5"><EmptyState title="No organizations found" description="Try a different search term or status filter." /></div>}
    </section></div>
}
