'use client'

import { Plus, Search } from 'lucide-react'
import { useState } from 'react'
import { usePortal } from '@/components/portal/PortalProvider'
import { EmptyState, PageHeader, StatusPill, formatDateTime } from '@/components/portal/PortalUi'

const roles = ['owner', 'administrator', 'support_agent', 'billing_agent', 'auditor']
const scopes = ['all_organizations', 'assigned_organizations', 'read_only']

export default function PortalUsersPage() {
  const { users, refresh } = usePortal()
  const [query, setQuery] = useState('')
  const [showCreate, setShowCreate] = useState(false)
  const [saving, setSaving] = useState('')
  const [feedback, setFeedback] = useState<{ tone: 'success' | 'error'; message: string } | null>(null)
  const [form, setForm] = useState({ full_name: '', email: '', password: '', platform_role: 'support_agent', platform_access_scope: 'all_organizations' })
  const filtered = users.filter((user) => !query || [user.full_name, user.email, user.platform_role].some((value) => value?.toLowerCase().includes(query.toLowerCase())))
  const request = async (method: 'POST' | 'PATCH', payload: Record<string, unknown>, success: string) => { setSaving(String(payload.profile_id || 'create')); setFeedback(null); try { const response = await fetch('/api/portal/users', { method, headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }); const result = await response.json(); if (!response.ok) throw new Error(result.error || 'Unable to update portal access.'); setFeedback({ tone: 'success', message: success }); await refresh(); return true } catch (caught) { setFeedback({ tone: 'error', message: caught instanceof Error ? caught.message : 'Unable to update portal access.' }); return false } finally { setSaving('') } }
  const create = async (event: React.FormEvent) => { event.preventDefault(); if (await request('POST', form, 'Portal operator created and audited.')) { setShowCreate(false); setForm({ full_name: '', email: '', password: '', platform_role: 'support_agent', platform_access_scope: 'all_organizations' }) } }
  const update = async (profileId: string, changes: Record<string, unknown>, message: string) => { await request('PATCH', { profile_id: profileId, confirmation: 'CONFIRM', ...changes }, message) }

  return <div className="space-y-6"><PageHeader eyebrow="Privileged access" title="Portal users" description="Create operators, change role and organization scope, suspend access, and review recent activity." action={<button onClick={() => setShowCreate((value) => !value)} className="inline-flex items-center gap-2 rounded-xl bg-[#152019] px-4 py-3 text-sm font-black text-white"><Plus className="h-4 w-4" />New portal user</button>} />
    {feedback ? <p role="status" className={`rounded-xl border px-4 py-3 text-sm font-bold ${feedback.tone === 'error' ? 'border-red-200 bg-red-50 text-red-700' : 'border-[#a9cf5b] bg-[#e9f6cc] text-[#496126]'}`}>{feedback.message}</p> : null}
    {showCreate ? <form onSubmit={create} className="grid gap-3 rounded-[24px] border border-[#8caf42] bg-[#dff7a8] p-5 sm:grid-cols-2 xl:grid-cols-6"><input required value={form.full_name} onChange={(event) => setForm({ ...form, full_name: event.target.value })} placeholder="Full name" aria-label="Full name" className="h-11 rounded-xl border border-black/10 bg-white px-3 text-sm" /><input required type="email" value={form.email} onChange={(event) => setForm({ ...form, email: event.target.value })} placeholder="Email address" aria-label="Email address" className="h-11 rounded-xl border border-black/10 bg-white px-3 text-sm" /><input required minLength={12} type="password" value={form.password} onChange={(event) => setForm({ ...form, password: event.target.value })} placeholder="Temporary password (12+ characters)" aria-label="Temporary password" className="h-11 rounded-xl border border-black/10 bg-white px-3 text-sm" /><select value={form.platform_role} onChange={(event) => setForm({ ...form, platform_role: event.target.value })} aria-label="Platform role" className="h-11 rounded-xl border border-black/10 bg-white px-3 text-sm font-bold">{roles.filter((role) => role !== 'owner').map((role) => <option key={role} value={role}>{role.replaceAll('_', ' ')}</option>)}</select><select value={form.platform_access_scope} onChange={(event) => setForm({ ...form, platform_access_scope: event.target.value })} aria-label="Access scope" className="h-11 rounded-xl border border-black/10 bg-white px-3 text-sm font-bold">{scopes.map((scope) => <option key={scope} value={scope}>{scope.replaceAll('_', ' ')}</option>)}</select><button disabled={saving === 'create'} className="h-11 rounded-xl bg-[#152019] px-4 text-sm font-black text-white disabled:opacity-50">{saving === 'create' ? 'Creating…' : 'Create access'}</button></form> : null}
    <section className="overflow-hidden rounded-[24px] border border-black/10 bg-white shadow-[0_18px_55px_rgba(20,31,24,0.06)]"><div className="border-b border-black/10 p-4"><label className="flex max-w-md items-center gap-2 rounded-xl border border-black/10 bg-[#f7f8f5] px-3"><Search className="h-4 w-4 text-[#718078]" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search operators" className="h-10 min-w-0 flex-1 bg-transparent text-sm outline-none" /></label></div>{filtered.length ? <div className="overflow-x-auto"><table className="w-full min-w-[980px] text-left"><thead><tr className="border-b border-black/8 text-[10px] font-black uppercase tracking-[.12em] text-[#718078]"><th className="px-5 py-3">Operator</th><th className="px-4 py-3">Role</th><th className="px-4 py-3">Scope</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Last active</th><th className="px-5 py-3 text-right">Access</th></tr></thead><tbody>{filtered.map((user) => <tr key={user.id} className="border-b border-black/5 last:border-0"><td className="px-5 py-4"><p className="text-sm font-black">{user.full_name}</p><p className="mt-1 text-xs text-[#718078]">{user.email}</p></td><td className="px-4 py-4"><select value={user.platform_role || 'administrator'} disabled={saving === user.id || user.platform_role === 'owner'} onChange={(event) => void update(user.id, { platform_role: event.target.value }, `${user.full_name}'s role was updated.`)} className="h-9 rounded-lg border border-black/10 bg-white px-2 text-xs font-black capitalize">{roles.map((role) => <option key={role} value={role}>{role.replaceAll('_', ' ')}</option>)}</select></td><td className="px-4 py-4"><select value={user.platform_access_scope} disabled={saving === user.id} onChange={(event) => void update(user.id, { platform_access_scope: event.target.value }, `${user.full_name}'s access scope was updated.`)} className="h-9 rounded-lg border border-black/10 bg-white px-2 text-xs font-black capitalize">{scopes.map((scope) => <option key={scope} value={scope}>{scope.replaceAll('_', ' ')}</option>)}</select></td><td className="px-4 py-4"><StatusPill value={user.is_active ? 'active' : 'inactive'} /></td><td className="px-4 py-4 text-xs font-bold text-[#718078]">{formatDateTime(user.portal_last_active_at)}</td><td className="px-5 py-4 text-right"><button disabled={saving === user.id || user.platform_role === 'owner'} onClick={() => { if (window.confirm('Confirm this audited access change.')) void update(user.id, { is_active: !user.is_active }, `Portal access was ${user.is_active ? 'suspended' : 'restored'}.`) }} className={`rounded-lg px-3 py-2 text-xs font-black disabled:opacity-40 ${user.is_active ? 'bg-red-50 text-red-700' : 'bg-[#e9f6cc] text-[#496126]'}`}>{user.is_active ? 'Suspend' : 'Restore'}</button></td></tr>)}</tbody></table></div> : <div className="p-5"><EmptyState title="No portal users found" description="Try a different search term." /></div>}</section>
  </div>
}
