'use client'

import { useState } from 'react'
import { Plus, Search } from 'lucide-react'
import { usePortal } from '@/components/portal/PortalProvider'
import { EmptyState, PageHeader, StatusPill, formatDateTime } from '@/components/portal/PortalUi'

export default function PortalUsersPage() {
  const { users, refresh } = usePortal()
  const [query, setQuery] = useState('')
  const [showCreate, setShowCreate] = useState(false)
  const [saving, setSaving] = useState(false)
  const [form, setForm] = useState({ full_name: '', email: '', password: '', platform_role: 'support_agent', platform_access_scope: 'all_organizations' })
  const filtered = users.filter((user) => !query || [user.full_name, user.email, user.platform_role].some((value) => value?.toLowerCase().includes(query.toLowerCase())))
  const create = async (event: React.FormEvent) => { event.preventDefault(); setSaving(true); const response = await fetch('/api/portal/users', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(form) }); if (response.ok) { setShowCreate(false); setForm({ full_name: '', email: '', password: '', platform_role: 'support_agent', platform_access_scope: 'all_organizations' }); await refresh() }; setSaving(false) }
  const toggle = async (id: string, active: boolean) => { if (!window.confirm('Confirm this audited access change.')) return; await fetch('/api/portal/users', { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ profile_id: id, is_active: active, confirmation: 'CONFIRM' }) }); await refresh() }
  return <div className="space-y-6"><PageHeader eyebrow="Privileged access" title="Portal users" description="Manage platform operators, access scope, status, and recent activity." action={<button onClick={() => setShowCreate((value) => !value)} className="inline-flex items-center gap-2 rounded-xl bg-[#152019] px-4 py-3 text-sm font-black text-white"><Plus className="h-4 w-4" />New portal user</button>} />
    {showCreate ? <form onSubmit={create} className="grid gap-3 rounded-[24px] border border-[#8caf42] bg-[#dff7a8] p-5 sm:grid-cols-2 xl:grid-cols-5"><input required value={form.full_name} onChange={(event) => setForm({ ...form, full_name: event.target.value })} placeholder="Full name" className="h-11 rounded-xl border border-black/10 bg-white px-3 text-sm" /><input required type="email" value={form.email} onChange={(event) => setForm({ ...form, email: event.target.value })} placeholder="Email address" className="h-11 rounded-xl border border-black/10 bg-white px-3 text-sm" /><input required minLength={8} type="password" value={form.password} onChange={(event) => setForm({ ...form, password: event.target.value })} placeholder="Temporary password" className="h-11 rounded-xl border border-black/10 bg-white px-3 text-sm" /><select value={form.platform_role} onChange={(event) => setForm({ ...form, platform_role: event.target.value })} className="h-11 rounded-xl border border-black/10 bg-white px-3 text-sm font-bold"><option value="support_agent">Support agent</option><option value="billing_manager">Billing manager</option><option value="administrator">Administrator</option></select><button disabled={saving} className="h-11 rounded-xl bg-[#152019] px-4 text-sm font-black text-white disabled:opacity-50">{saving ? 'Creating…' : 'Create access'}</button></form> : null}
    <section className="overflow-hidden rounded-[24px] border border-black/10 bg-white shadow-[0_18px_55px_rgba(20,31,24,0.06)]"><div className="border-b border-black/10 p-4"><label className="flex max-w-md items-center gap-2 rounded-xl border border-black/10 bg-[#f7f8f5] px-3"><Search className="h-4 w-4 text-[#718078]" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search operators" className="h-10 min-w-0 flex-1 bg-transparent text-sm outline-none" /></label></div>{filtered.length ? <div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left"><thead><tr className="border-b border-black/8 text-[10px] font-black uppercase tracking-[.12em] text-[#718078]"><th className="px-5 py-3">Operator</th><th className="px-4 py-3">Role</th><th className="px-4 py-3">Scope</th><th className="px-4 py-3">Last active</th><th className="px-5 py-3 text-right">Access</th></tr></thead><tbody>{filtered.map((user) => <tr key={user.id} className="border-b border-black/5 last:border-0"><td className="px-5 py-4"><p className="text-sm font-black">{user.full_name}</p><p className="mt-1 text-xs text-[#718078]">{user.email}</p></td><td className="px-4 py-4"><StatusPill value={user.platform_role || 'administrator'} /></td><td className="px-4 py-4 text-xs font-bold capitalize text-[#5f6d64]">{user.platform_access_scope.replaceAll('_', ' ')}</td><td className="px-4 py-4 text-xs font-bold text-[#718078]">{formatDateTime(user.portal_last_active_at)}</td><td className="px-5 py-4 text-right"><button onClick={() => void toggle(user.id, !user.is_active)} className={`rounded-lg px-3 py-2 text-xs font-black ${user.is_active ? 'bg-red-50 text-red-700' : 'bg-[#e9f6cc] text-[#496126]'}`}>{user.is_active ? 'Suspend' : 'Restore'}</button></td></tr>)}</tbody></table></div> : <div className="p-5"><EmptyState title="No portal users found" description="Try a different search term." /></div>}</section>
  </div>
}
