'use client'

import { useMemo, useState } from 'react'
import { Download, Search } from 'lucide-react'
import { usePortal } from '@/components/portal/PortalProvider'
import { EmptyState, PageHeader, StatusPill, formatDateTime } from '@/components/portal/PortalUi'

export default function AuditLogsPage() {
  const { auditEvents } = usePortal()
  const [query, setQuery] = useState('')
  const [scope, setScope] = useState('all')
  const filtered = useMemo(() => auditEvents.filter((event) => (scope === 'all' || event.entity_type === scope) && (!query || [event.action_type, event.entity_type, event.organization?.name, event.actor?.full_name].some((value) => value?.toLowerCase().includes(query.toLowerCase())))), [auditEvents, query, scope])
  const exportCsv = () => { const lines = [['Timestamp', 'Action', 'Entity', 'Organization', 'Actor'], ...filtered.map((event) => [event.created_at, event.action_type, event.entity_type, event.organization?.name || 'Platform', event.actor?.full_name || 'System'])]; const blob = new Blob([lines.map((line) => line.map((cell) => `"${String(cell).replaceAll('"', '""')}"`).join(',')).join('\n')], { type: 'text/csv' }); const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = `portal-audit-${new Date().toISOString().slice(0, 10)}.csv`; link.click(); URL.revokeObjectURL(url) }
  return <div className="space-y-6"><PageHeader eyebrow="Immutable evidence" title="Audit logs" description="Search privileged actions across organizations, operators, and platform workflows." action={<button onClick={exportCsv} className="inline-flex items-center gap-2 rounded-xl bg-[#152019] px-4 py-3 text-sm font-black text-white"><Download className="h-4 w-4" />Export CSV</button>} />
    <section className="overflow-hidden rounded-[24px] border border-black/10 bg-white shadow-[0_18px_55px_rgba(20,31,24,0.06)]"><div className="flex flex-col gap-3 border-b border-black/10 p-4 sm:flex-row"><label className="flex min-w-0 flex-1 items-center gap-2 rounded-xl border border-black/10 bg-[#f7f8f5] px-3"><Search className="h-4 w-4 text-[#718078]" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search action, actor, or organization" className="h-10 min-w-0 flex-1 bg-transparent text-sm outline-none" /></label><select value={scope} onChange={(event) => setScope(event.target.value)} className="h-10 rounded-xl border border-black/10 bg-white px-3 text-sm font-bold"><option value="all">All entities</option><option value="organization">Organizations</option><option value="profile">Profiles</option><option value="support_ticket">Support tickets</option><option value="platform_support_task">Tasks</option></select></div>{filtered.length ? <div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left"><thead><tr className="border-b border-black/8 text-[10px] font-black uppercase tracking-[.12em] text-[#718078]"><th className="px-5 py-3">Timestamp</th><th className="px-4 py-3">Action</th><th className="px-4 py-3">Entity</th><th className="px-4 py-3">Organization</th><th className="px-5 py-3">Actor</th></tr></thead><tbody>{filtered.map((event) => <tr key={event.id} className="border-b border-black/5 last:border-0 hover:bg-[#f8faf6]"><td className="px-5 py-4 text-xs font-bold text-[#718078]">{formatDateTime(event.created_at)}</td><td className="px-4 py-4 text-sm font-black capitalize">{event.action_type.replaceAll('_', ' ')}</td><td className="px-4 py-4"><StatusPill value={event.entity_type} /></td><td className="px-4 py-4 text-sm font-bold">{event.organization?.name || 'Platform-wide'}</td><td className="px-5 py-4"><p className="text-sm font-bold">{event.actor?.full_name || String(event.metadata.actor_name || 'System')}</p><p className="text-xs text-[#718078]">{event.actor?.email || String(event.metadata.actor_email || '')}</p></td></tr>)}</tbody></table></div> : <div className="p-5"><EmptyState title="No audit events found" description="Adjust your search or entity filter." /></div>}</section>
  </div>
}
