'use client'

import { Download, PieChart, TrendingUp, Users } from 'lucide-react'
import { usePortal } from '@/components/portal/PortalProvider'
import { PageHeader, Panel } from '@/components/portal/PortalUi'

export default function ReportsPage() {
  const { organizations, metrics, tickets, tasks } = usePortal()
  const resolved = tickets.filter((ticket) => ['resolved', 'closed'].includes(ticket.status)).length
  const paid = organizations.filter((organization) => organization.plan !== 'free').length
  const exportCsv = () => { const rows = [['Organization', 'Status', 'Plan', 'Users', 'Staff', 'Subscription'], ...organizations.map((item) => [item.name, item.status, item.plan_name, item.user_count, item.staff_count, item.subscription_status || 'none'])]; const blob = new Blob([rows.map((row) => row.map((cell) => `"${cell}"`).join(',')).join('\n')], { type: 'text/csv' }); const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = `platform-report-${new Date().toISOString().slice(0, 10)}.csv`; link.click(); URL.revokeObjectURL(url) }
  const plans = ['free', 'starter', 'professional', 'enterprise'].map((plan) => ({ plan, count: organizations.filter((organization) => organization.plan === plan).length }))
  return <div className="space-y-6"><PageHeader eyebrow="Decision intelligence" title="Platform reports" description="Commercial, customer, service, and operational performance in one executive view." action={<button onClick={exportCsv} className="inline-flex items-center gap-2 rounded-xl bg-[#152019] px-4 py-3 text-sm font-black text-white"><Download className="h-4 w-4" />Export portfolio</button>} />
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Kpi label="Annual run rate" value={`£${metrics.annualRevenue.toLocaleString()}`} detail={`£${metrics.monthlyRevenue.toLocaleString()} MRR`} /><Kpi label="Paid conversion" value={`${organizations.length ? Math.round(paid / organizations.length * 100) : 0}%`} detail={`${paid} paid organizations`} /><Kpi label="Support resolution" value={`${tickets.length ? Math.round(resolved / tickets.length * 100) : 100}%`} detail={`${resolved} of ${tickets.length} cases closed`} /><Kpi label="Task completion" value={`${tasks.length ? Math.round(tasks.filter((task) => task.status === 'completed').length / tasks.length * 100) : 100}%`} detail={`${tasks.filter((task) => !['completed', 'cancelled'].includes(task.status)).length} active tasks`} /></section>
    <section className="grid gap-5 xl:grid-cols-2"><Panel title="Plan distribution" description="Customer portfolio by commercial package."><div className="space-y-4">{plans.map((item) => { const percent = organizations.length ? Math.round(item.count / organizations.length * 100) : 0; return <div key={item.plan}><div className="flex justify-between text-sm font-black capitalize"><span>{item.plan}</span><span>{item.count} · {percent}%</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-black/8"><span className="block h-full rounded-full bg-[#8aae3d]" style={{ width: `${percent}%` }} /></div></div> })}</div></Panel><Panel title="Operating scale" description="People and organizations currently managed by the platform."><div className="grid gap-3 sm:grid-cols-2"><Scale icon={<Users />} value={metrics.staff} label="Staff records" /><Scale icon={<Users />} value={metrics.users} label="Workspace users" /><Scale icon={<TrendingUp />} value={metrics.activeOrganizations} label="Active tenants" /><Scale icon={<PieChart />} value={metrics.cancelledSubscriptions} label="Cancelled subscriptions" /></div></Panel></section>
  </div>
}
function Kpi({ label, value, detail }: { label: string; value: string; detail: string }) { return <article className="rounded-[22px] border border-black/10 bg-white p-5"><p className="text-[10px] font-black uppercase tracking-[.14em] text-[#718078]">{label}</p><p className="mt-4 text-3xl font-black tracking-[-.04em]">{value}</p><p className="mt-1 text-xs font-bold text-[#718078]">{detail}</p></article> }
function Scale({ icon, value, label }: { icon: React.ReactNode; value: number; label: string }) { return <div className="rounded-xl bg-[#f7f8f5] p-4"><span className="[&>svg]:h-4 [&>svg]:w-4 text-[#78924e]">{icon}</span><p className="mt-4 text-2xl font-black">{value.toLocaleString()}</p><p className="mt-1 text-xs font-bold text-[#718078]">{label}</p></div> }
