'use client'

import { CalendarClock, Download, PieChart, Plus, TrendingUp, Users } from 'lucide-react'
import { useState } from 'react'
import { usePortal } from '@/components/portal/PortalProvider'
import { EmptyState, PageHeader, Panel, formatDateTime } from '@/components/portal/PortalUi'

export default function ReportsPage() {
  const { organizations, metrics, tickets, tasks, reportSchedules, refresh } = usePortal()
  const [showSchedule, setShowSchedule] = useState(false)
  const [form, setForm] = useState({ name: '', report_type: 'portfolio', cadence: 'weekly', recipients: '' })
  const [feedback, setFeedback] = useState('')
  const resolved = tickets.filter((ticket) => ['resolved', 'closed'].includes(ticket.status)).length
  const paid = organizations.filter((organization) => organization.plan !== 'free').length
  const plans = ['free', 'starter', 'professional', 'enterprise'].map((plan) => ({ plan, count: organizations.filter((organization) => organization.plan === plan).length }))
  const exportCsv = () => { const rows = [['Organization', 'Status', 'Plan', 'Users', 'Staff', 'Subscription'], ...organizations.map((item) => [item.name, item.status, item.plan_name, item.user_count, item.staff_count, item.subscription_status || 'none'])]; download(rows, `platform-report-${new Date().toISOString().slice(0, 10)}.csv`) }
  const schedule = async (event: React.FormEvent) => { event.preventDefault(); setFeedback(''); const response = await fetch('/api/portal/maturity', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ kind: 'report_schedule', ...form, recipients: form.recipients.split(',').map((item) => item.trim()).filter(Boolean) }) }); const result = await response.json(); if (!response.ok) { setFeedback(result.error || 'Unable to schedule report.'); return }; setFeedback('Report delivery schedule created.'); setShowSchedule(false); setForm({ name: '', report_type: 'portfolio', cadence: 'weekly', recipients: '' }); await refresh() }
  return <div className="space-y-6"><PageHeader eyebrow="Decision intelligence" title="Platform reports" description="Commercial, customer, service, and operational performance with export and scheduled delivery." action={<div className="flex flex-wrap gap-2"><button onClick={() => setShowSchedule((value) => !value)} className="inline-flex items-center gap-2 rounded-xl bg-white px-4 py-3 text-sm font-black ring-1 ring-black/10"><Plus className="h-4 w-4" />Schedule</button><button onClick={exportCsv} className="inline-flex items-center gap-2 rounded-xl bg-[#152019] px-4 py-3 text-sm font-black text-white"><Download className="h-4 w-4" />Export portfolio</button></div>} />
    {feedback ? <p role="status" className="rounded-xl border border-[#a9cf5b] bg-[#e9f6cc] px-4 py-3 text-sm font-bold text-[#496126]">{feedback}</p> : null}
    {showSchedule ? <form onSubmit={schedule} className="grid gap-3 rounded-[24px] border border-[#8caf42] bg-[#dff7a8] p-5 md:grid-cols-2 xl:grid-cols-5"><input required value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} placeholder="Schedule name" className="h-11 rounded-xl border border-black/10 bg-white px-3 text-sm" /><select value={form.report_type} onChange={(event) => setForm({ ...form, report_type: event.target.value })} className="h-11 rounded-xl border border-black/10 bg-white px-3 text-sm font-bold">{['portfolio', 'billing', 'security', 'support', 'audit'].map((item) => <option key={item}>{item}</option>)}</select><select value={form.cadence} onChange={(event) => setForm({ ...form, cadence: event.target.value })} className="h-11 rounded-xl border border-black/10 bg-white px-3 text-sm font-bold">{['daily', 'weekly', 'monthly'].map((item) => <option key={item}>{item}</option>)}</select><input required value={form.recipients} onChange={(event) => setForm({ ...form, recipients: event.target.value })} placeholder="Recipients, comma separated" className="h-11 rounded-xl border border-black/10 bg-white px-3 text-sm" /><button className="h-11 rounded-xl bg-[#152019] text-sm font-black text-white">Create schedule</button></form> : null}
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Kpi label="Annual run rate" value={`£${metrics.annualRevenue.toLocaleString()}`} detail={`£${metrics.monthlyRevenue.toLocaleString()} MRR`} /><Kpi label="Paid conversion" value={`${organizations.length ? Math.round(paid / organizations.length * 100) : 0}%`} detail={`${paid} paid organizations`} /><Kpi label="Support resolution" value={`${tickets.length ? Math.round(resolved / tickets.length * 100) : 100}%`} detail={`${resolved} of ${tickets.length} cases closed`} /><Kpi label="Task completion" value={`${tasks.length ? Math.round(tasks.filter((task) => task.status === 'completed').length / tasks.length * 100) : 100}%`} detail={`${tasks.filter((task) => !['completed', 'cancelled'].includes(task.status)).length} active tasks`} /></section>
    <section className="grid gap-5 xl:grid-cols-2"><Panel title="Plan distribution" description="Customer portfolio by commercial package."><div className="space-y-4">{plans.map((item) => { const percent = organizations.length ? Math.round(item.count / organizations.length * 100) : 0; return <div key={item.plan}><div className="flex justify-between text-sm font-black capitalize"><span>{item.plan}</span><span>{item.count} · {percent}%</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-black/8"><span className="block h-full rounded-full bg-[#8aae3d]" style={{ width: `${percent}%` }} /></div></div> })}</div></Panel><Panel title="Operating scale"><div className="grid gap-3 sm:grid-cols-2"><Scale icon={<Users />} value={metrics.staff} label="Staff records" /><Scale icon={<Users />} value={metrics.users} label="Workspace users" /><Scale icon={<TrendingUp />} value={metrics.activeOrganizations} label="Active tenants" /><Scale icon={<PieChart />} value={metrics.cancelledSubscriptions} label="Cancelled subscriptions" /></div></Panel></section>
    <Panel title="Scheduled delivery" description="Recurring report exports and their next planned run.">{reportSchedules.length ? <div className="divide-y divide-black/5">{reportSchedules.map((schedule) => <div key={schedule.id} className="flex items-center gap-3 py-3"><CalendarClock className="h-4 w-4 text-[#78924e]" /><div className="min-w-0 flex-1"><p className="truncate text-sm font-black">{schedule.name}</p><p className="text-xs capitalize text-[#718078]">{schedule.report_type} · {schedule.cadence} · {schedule.recipients.join(', ')}</p></div><span className="text-xs font-bold text-[#718078]">{formatDateTime(schedule.next_run_at)}</span></div>)}</div> : <EmptyState title="No scheduled reports" description="Create a schedule to deliver recurring operational reporting." />}</Panel>
  </div>
}

function download(rows: Array<Array<string | number>>, filename: string) { const blob = new Blob([rows.map((row) => row.map((cell) => `"${String(cell).replaceAll('"', '""')}"`).join(',')).join('\n')], { type: 'text/csv' }); const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = filename; link.click(); URL.revokeObjectURL(url) }
function Kpi({ label, value, detail }: { label: string; value: string; detail: string }) { return <article className="rounded-[22px] border border-black/10 bg-white p-5"><p className="text-[10px] font-black uppercase tracking-[.14em] text-[#718078]">{label}</p><p className="mt-4 text-3xl font-black tracking-[-.04em]">{value}</p><p className="mt-1 text-xs font-bold text-[#718078]">{detail}</p></article> }
function Scale({ icon, value, label }: { icon: React.ReactNode; value: number; label: string }) { return <div className="rounded-xl bg-[#f7f8f5] p-4"><span className="[&>svg]:h-4 [&>svg]:w-4 text-[#78924e]">{icon}</span><p className="mt-4 text-2xl font-black">{value.toLocaleString()}</p><p className="mt-1 text-xs font-bold text-[#718078]">{label}</p></div> }
