'use client'

import Link from 'next/link'
import { AlertTriangle, BellRing, Check, CheckCircle2, CircleDollarSign, Clock3, ShieldAlert, UserCheck } from 'lucide-react'
import { useMemo, useState } from 'react'
import { usePortal } from '@/components/portal/PortalProvider'
import { EmptyState, PageHeader, StatusPill, formatDateTime } from '@/components/portal/PortalUi'

export default function NotificationsPage() {
  const { tasks, approvals, tickets, organizations, notificationStates, refresh } = usePortal()
  const [now] = useState(() => Date.now())
  const [filter, setFilter] = useState<'all' | 'unread' | 'owned'>('all')
  const [saving, setSaving] = useState('')
  const states = useMemo(() => new Map(notificationStates.map((item) => [item.item_key, item])), [notificationStates])
  const items = [
    ...tasks.filter((task) => !['completed', 'cancelled'].includes(task.status) && task.due_at && new Date(task.due_at).getTime() < now).map((task) => ({ id: `task-${task.id}`, icon: Clock3, title: `Overdue: ${task.title}`, detail: `${task.organization?.name} · due ${formatDateTime(task.due_at)}`, tone: 'urgent', href: '/portal/tasks' })),
    ...approvals.filter((approval) => approval.status === 'pending').map((approval) => ({ id: `approval-${approval.id}`, icon: ShieldAlert, title: `Approval required: ${approval.action_type.replaceAll('_', ' ')}`, detail: `${approval.organization?.name || 'Platform-wide'} · requested ${formatDateTime(approval.created_at)}`, tone: 'high', href: '/portal/tasks' })),
    ...tickets.filter((ticket) => !ticket.first_response_at && ticket.first_response_due_at && new Date(ticket.first_response_due_at).getTime() < now).map((ticket) => ({ id: `ticket-${ticket.id}`, icon: AlertTriangle, title: `Support SLA breached: ${ticket.subject}`, detail: `${ticket.organization?.name} · case #${ticket.ticket_number}`, tone: 'urgent', href: `/portal/support?ticket=${ticket.id}` })),
    ...organizations.filter((organization) => ['cancelled', 'past_due', 'unpaid'].includes(organization.subscription_status || '')).map((organization) => ({ id: `billing-${organization.id}`, icon: CircleDollarSign, title: `Billing intervention: ${organization.name}`, detail: `${organization.plan_name} · ${organization.subscription_status}`, tone: 'high', href: `/portal/organizations/${organization.id}` })),
  ]
  const visible = items.filter((item) => filter === 'all' || (filter === 'unread' ? !states.get(item.id)?.read_at : Boolean(states.get(item.id)?.owner_profile_id)))
  const unread = items.filter((item) => !states.get(item.id)?.read_at).length
  const update = async (itemKey: string, changes: { read?: boolean; acknowledged?: boolean; assign_to_me?: boolean }) => { setSaving(itemKey); try { const response = await fetch('/api/portal/maturity', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ kind: 'notification_state', item_key: itemKey, ...changes }) }); if (!response.ok) throw new Error('Unable to update notification.'); await refresh() } finally { setSaving('') } }
  return <div className="space-y-6"><PageHeader eyebrow="Action centre" title="Notifications" description="A persistent, owned work inbox generated from overdue work, SLA breaches, approvals, and commercial risk." />
    <section className="grid gap-3 sm:grid-cols-4"><Summary icon={<BellRing />} label="Requires action" value={items.length} /><Summary icon={<AlertTriangle />} label="Urgent" value={items.filter((item) => item.tone === 'urgent').length} /><Summary icon={<BellRing />} label="Unread" value={unread} /><Summary icon={<CheckCircle2 />} label="Acknowledged" value={notificationStates.filter((item) => item.acknowledged_at).length} /></section>
    <div className="flex flex-wrap gap-2">{(['all', 'unread', 'owned'] as const).map((item) => <button key={item} type="button" onClick={() => setFilter(item)} className={`rounded-xl px-4 py-2 text-xs font-black capitalize ${filter === item ? 'bg-[#152019] text-white' : 'bg-white ring-1 ring-black/10'}`}>{item}</button>)}</div>
    <section className="rounded-[24px] border border-black/10 bg-white p-5 shadow-[0_18px_55px_rgba(20,31,24,0.06)] sm:p-6">{visible.length ? <div className="divide-y divide-black/5">{visible.map((item) => { const Icon = item.icon; const state = states.get(item.id); return <article key={item.id} className={`flex flex-col gap-3 py-4 first:pt-0 last:pb-0 sm:flex-row sm:items-center ${state?.read_at ? 'opacity-65' : ''}`}><Link href={item.href} onClick={() => void update(item.id, { read: true })} className="flex min-w-0 flex-1 items-center gap-4"><span className={`flex h-11 w-11 shrink-0 items-center justify-center rounded-xl ${item.tone === 'urgent' ? 'bg-red-50 text-red-700' : 'bg-amber-50 text-amber-700'}`}><Icon className="h-5 w-5" /></span><div className="min-w-0 flex-1"><p className="truncate text-sm font-black">{item.title}</p><p className="mt-1 truncate text-xs text-[#718078]">{item.detail}</p></div><StatusPill value={item.tone} /></Link><div className="flex justify-end gap-2"><button disabled={saving === item.id} onClick={() => void update(item.id, { read: true, assign_to_me: true })} className="inline-flex items-center gap-1 rounded-lg bg-[#eef1eb] px-3 py-2 text-xs font-black"><UserCheck className="h-3.5 w-3.5" />Own</button><button disabled={saving === item.id} onClick={() => void update(item.id, { read: true, acknowledged: true, assign_to_me: Boolean(state?.owner_profile_id) })} className="inline-flex items-center gap-1 rounded-lg bg-[#152019] px-3 py-2 text-xs font-black text-white"><Check className="h-3.5 w-3.5" />Acknowledge</button></div></article> })}</div> : <EmptyState title="Nothing in this view" description="There are no matching operational notifications." />}</section>
  </div>
}

function Summary({ icon, label, value }: { icon: React.ReactNode; label: string; value: number }) { return <article className="rounded-[22px] border border-black/10 bg-white p-5"><div className="flex items-center justify-between"><p className="text-[10px] font-black uppercase tracking-[.14em] text-[#718078]">{label}</p><span className="[&>svg]:h-4 [&>svg]:w-4 text-[#78924e]">{icon}</span></div><p className="mt-4 text-3xl font-black">{value}</p></article> }
