'use client'

import Link from 'next/link'
import { ArrowUpRight, Building2, CircleDollarSign, Clock3, ShieldAlert, Users } from 'lucide-react'
import { usePortal } from '@/components/portal/PortalProvider'
import { LoadingState, PageHeader, Panel, StatusPill } from '@/components/portal/PortalUi'

export default function PortalDashboardPage() {
  const { metrics, organizations, tickets, loading, error } = usePortal()
  const openTickets = tickets.filter((ticket) => !['resolved', 'closed'].includes(ticket.status))
  const attention = organizations.filter((organization) => ['suspended', 'paused'].includes(organization.status) || organization.subscription_status === 'cancelled' || (organization.staff_limit && organization.staff_count / organization.staff_limit >= .85))
  if (loading && organizations.length === 0) return <LoadingState />
  return <div className="space-y-6">
    <PageHeader eyebrow="Platform pulse" title="Operations overview" description="Commercial health, tenant risk, and service performance—focused on what needs action today." action={<Link href="/portal/organizations" className="inline-flex items-center gap-2 rounded-xl bg-[#152019] px-4 py-3 text-sm font-black text-white">Open directory <ArrowUpRight className="h-4 w-4" /></Link>} />
    {error ? <p className="rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm font-bold text-red-700">{error}</p> : null}
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={<CircleDollarSign />} label="Monthly recurring revenue" value={`£${metrics.monthlyRevenue.toLocaleString()}`} detail={`£${metrics.annualRevenue.toLocaleString()} annual run rate`} accent /><Metric icon={<Building2 />} label="Active organizations" value={metrics.activeOrganizations.toLocaleString()} detail={`${metrics.organizations} total tenants`} /><Metric icon={<Users />} label="People managed" value={(metrics.users + metrics.staff).toLocaleString()} detail={`${metrics.users} users · ${metrics.staff} staff`} /><Metric icon={<Clock3 />} label="Open support cases" value={openTickets.length.toLocaleString()} detail={`${openTickets.filter((ticket) => ticket.priority === 'urgent').length} urgent`} /></section>
    <section className="grid gap-5 xl:grid-cols-[1.15fr_.85fr]"><Panel title="Organizations needing attention" description="Suspended accounts, billing risk, and tenants nearing capacity.">{attention.length ? <div className="divide-y divide-black/5">{attention.slice(0, 7).map((organization) => <Link key={organization.id} href={`/portal/organizations/${organization.id}`} className="flex items-center gap-3 py-3 first:pt-0 last:pb-0"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#edf2e8] font-black">{organization.name[0]}</span><div className="min-w-0 flex-1"><p className="truncate text-sm font-black">{organization.name}</p><p className="mt-0.5 text-xs text-[#718078]">{organization.staff_count} staff · {organization.plan_name}</p></div><StatusPill value={organization.status} /></Link>)}</div> : <p className="text-sm text-[#718078]">No organizations currently require intervention.</p>}</Panel><Panel title="Service desk" description="The latest unresolved customer cases.">{openTickets.length ? <div className="space-y-3">{openTickets.slice(0, 5).map((ticket) => <Link key={ticket.id} href={`/portal/support?ticket=${ticket.id}`} className="block rounded-xl border border-black/8 bg-[#f7f8f5] p-3"><div className="flex items-center gap-2"><ShieldAlert className="h-4 w-4 text-[#66814a]" /><p className="min-w-0 flex-1 truncate text-sm font-black">{ticket.subject}</p><StatusPill value={ticket.priority} /></div><p className="mt-2 text-xs text-[#718078]">#{ticket.ticket_number} · {ticket.organization?.name || 'Unknown organization'}</p></Link>)}</div> : <p className="text-sm text-[#718078]">The support queue is clear.</p>}</Panel></section>
  </div>
}

function Metric({ icon, label, value, detail, accent = false }: { icon: React.ReactNode; label: string; value: string; detail: string; accent?: boolean }) { return <article className={`relative overflow-hidden rounded-[24px] border p-5 ${accent ? 'border-[#91bd37] bg-[#b8f43d]' : 'border-black/10 bg-white'}`}><div className="flex items-start justify-between"><p className="text-[10px] font-black uppercase tracking-[0.14em] opacity-55">{label}</p><span className="[&>svg]:h-5 [&>svg]:w-5 opacity-55">{icon}</span></div><p className="mt-5 text-3xl font-black tracking-[-0.04em]">{value}</p><p className="mt-1 text-xs font-bold opacity-55">{detail}</p></article> }
