'use client'

import Link from 'next/link'
import { AlertTriangle, ArrowUpRight, CalendarDays, CircleDollarSign, CreditCard, TrendingUp } from 'lucide-react'
import { usePortal } from '@/components/portal/PortalProvider'
import { PageHeader, Panel, StatusPill, formatDate } from '@/components/portal/PortalUi'

export default function BillingPage() {
  const { metrics, organizations } = usePortal()
  const paid = organizations.filter((organization) => organization.plan !== 'free')
  const risk = paid.filter((organization) => ['cancelled', 'past_due', 'unpaid'].includes(organization.subscription_status || ''))
  return <div className="space-y-6"><PageHeader eyebrow="Commercial operations" title="Billing and revenue" description="Subscription health, recurring revenue, renewal timing, and accounts requiring intervention." />
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Stat icon={<CircleDollarSign />} label="MRR" value={`£${metrics.monthlyRevenue.toLocaleString()}`} detail="Recurring monthly revenue" /><Stat icon={<TrendingUp />} label="ARR" value={`£${metrics.annualRevenue.toLocaleString()}`} detail="Annual run rate" /><Stat icon={<CreditCard />} label="Paid accounts" value={paid.length.toLocaleString()} detail={`${organizations.length} total organizations`} /><Stat icon={<AlertTriangle />} label="Billing risk" value={risk.length.toLocaleString()} detail="Accounts requiring action" risk={risk.length > 0} /></section>
    <section className="grid gap-5 xl:grid-cols-[1.15fr_.85fr]"><Panel title="Subscription portfolio" description="Current package and subscription state for every paid customer."><div className="divide-y divide-black/5">{paid.slice(0, 12).map((organization) => <Link key={organization.id} href={`/portal/organizations/${organization.id}`} className="flex items-center gap-3 py-3 first:pt-0 last:pb-0"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#edf2e8] font-black">{organization.name[0]}</span><div className="min-w-0 flex-1"><p className="truncate text-sm font-black">{organization.name}</p><p className="text-xs text-[#718078]">{organization.plan_name} · £{(organization.monthly_price || 0).toLocaleString()}/month</p></div><StatusPill value={organization.subscription_status || organization.status} /><ArrowUpRight className="h-4 w-4 text-[#718078]" /></Link>)}</div></Panel><Panel title="Upcoming renewals" description="Subscription periods ending soonest."><div className="space-y-3">{paid.filter((organization) => organization.subscription_period_end).sort((a, b) => new Date(a.subscription_period_end!).getTime() - new Date(b.subscription_period_end!).getTime()).slice(0, 8).map((organization) => <div key={organization.id} className="flex items-center gap-3 rounded-xl bg-[#f7f8f5] p-3"><CalendarDays className="h-4 w-4 text-[#78924e]" /><div className="min-w-0 flex-1"><p className="truncate text-sm font-black">{organization.name}</p><p className="text-xs text-[#718078]">{organization.plan_name}</p></div><span className="text-xs font-black">{formatDate(organization.subscription_period_end)}</span></div>)}</div></Panel></section>
  </div>
}
function Stat({ icon, label, value, detail, risk = false }: { icon: React.ReactNode; label: string; value: string; detail: string; risk?: boolean }) { return <article className={`rounded-[22px] border p-5 ${risk ? 'border-red-200 bg-red-50' : 'border-black/10 bg-white'}`}><div className="flex justify-between"><p className="text-[10px] font-black uppercase tracking-[.14em] opacity-55">{label}</p><span className="[&>svg]:h-4 [&>svg]:w-4 opacity-55">{icon}</span></div><p className="mt-4 text-3xl font-black">{value}</p><p className="mt-1 text-xs font-bold opacity-55">{detail}</p></article> }
